const DEFAULT_STATES_OF_EXPENSES = {
  INVOICE_COST: 'INVOICE COST',
  TRANSPORTATION: 'TRANSPORTATION',
  CUSTOMS_DUTY: 'CUSTOMS DUTY',
  LOADING_UNLOADING: 'LOADING/UNLOADING',
};

export default DEFAULT_STATES_OF_EXPENSES;
