export const generalErrorTypes = {
  NOT_EMPTY0: 'NOT_EMPTY0',
  NOT_EMPTY5: 'NOT_EMPTY5',
  NOT_LONGER30: 'NOT_LONGER30',
  NOT_EMPTY10: 'NOT_EMPTY10',
  RADIO_NOT_SELECTED: 'RADIO_NOT_SELECTED',
  NOT_A_NUMBER: 'NOT_A_NUMBER',
  IS_NEGATIVE_OR_ZERO: 'IS_NEGATIVE_OR_ZERO',
  FILE_NOT_PROVIDED: 'FILE_NOT_PROVIDED',
};

export const fileDataErrorTypes = {
  WRONG_COL_NUMBER: 'FILE_DATA/WRONG_COL_NUMBER',
  NO_EMPTY_CELLS: 'FILE_DATA/NO_EMPTY_CELLS',
  WRONG_HEADER: 'FILE_DATA/WRONG_HEADER',
  AT_LEAST_ONE_PRODUCT: 'FILE_DATA/AT_LEAST_ONE_PRODUCT',
  PRICE_IS_NOT_NUMBER: 'FILE_DATA/PRICE_IS_NOT_NUMBER',
  QTY_IS_NOT_NUMBER: 'FILE_DATA/QTY_IS_NOT_NUMBER',
  G_WEIGHT_IS_NOT_NUMBER: 'FILE_DATA/G_WEIGHT_IS_NOT_NUMBER',
  CBM_IS_NOT_NUMBER: 'FILE_DATA/CBM_IS_NOT_NUMBER',
  CURRENCY_IS_NUMBER: 'FILE_DATA/CURRENCY_IS_NUMBER',
  UM_IS_NUMBER: 'FILE_DATA/UM_IS_NUMBER',
  WRONG_CURRENCY: 'FILE_DATA/WRONG_CURRENCY',
};

export default {
  generalErrorTypes,
  fileDataErrorTypes,
};
